project:
  type: book

book:
  date: "21/10/2024"
  chapters:
    - index.qmd  # mandatory for a book
    # - intro.qmd
    # - summary.qmd
    # - references.qmd

format:
  pdf:
    # Generic options
    lang: en-us

    # TODO move this to _extensions/novel-pdf/_extension.yml
    # Basic template config
    template: novel-template.tex
    pdf-engine: lualatex  # Madatory: novel class only works with LuaLaTeX
    # Compilation options
    # See: https://quarto.org/docs/output-formats/pdf-engine.html#pdf-compilation
    latex-min-runs: 1
    latex-max-runs: 1
    latex-clean: true
